### ISSUE TITLE
Consider not forking hlviewer.js

### ISSUE THREAD

**Issue by steren** [x8BitRain/webhl#9]
It seems that this repo includes the source of `hlviewer.js`

It might be better for maintenance it simply had a dependecy on https://github.com/skyrim/hlviewer.js, so that any improvement made to hlviewer.js would ultimately make its way to this project.

**Comment by x8BitRain** [comment]
That would be ideal but a lot of the `hlviewer.js` source needed to be modified and restructured a lot in order to get the idea working. `Game.ts`, `Loader.ts`, a lot of the `PlayerInterface` and `WorldScene.ts`, nor is it compatible with my build tools out of the box. Unless you're talking about some specific dependency setup that I'm not aware of.

**Comment by steren** [comment]
One solution could be to send changes to hlviewer.js so that it is able to load from files in memory instead of only loading files from the server.

**Comment by x8BitRain** [comment]
That's a good idea, I'll ask if the hlviewerjs creator would like this to happen. But again, the code changes to it are fairly large and due to hlviewerjs being built as a commonJS module meant to be loaded via a <script> tag and not importable as an ES module, this wouldn't help me much in my approach in making webhl an SPA, for now any additions to hlviewerjs would be  added manually, but I'll see what I can do.
